### ISSUE TITLE
Authorization failed.

### ISSUE THREAD

**Issue by embeddedsamurai** [T3aHat/DeepLopener_PRO#2]
I entered a valid key but got the following error:

 ------------------------------------------------------------- 
 DeepLopener PRO Error: 403
 Authorization failed. Please supply a valid auth_key parameter.

**Comment by T3aHat** [comment]
ご連絡いただきありがとうございます．おそらく入力されたAPI_KEYを隠す部分で何らかの問題が起きたものと考えられますので，諸々検証してみます．

**Comment by T3aHat** [comment]
@embeddedsamurai 様，
Chromeにはログインした状態で使用されていましたか?
#3 のようにログインしていない状態かログインに問題がある場合に，API_KEYが`null`になる問題を見つけました．お時間がある時にお答えいただけると幸いです．  

(以下技術的なお話)  
options画面で右クリックをして`検証`に入り，[Storage Area Explorer](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb)を入れて`Storage Explorer`から`chrome.storage.sync`を見ると，保存された各種変数の値を見ることができます．  
API_KEYは`deeeplpro_apikey`に格納されており，ログインしていない端末にて`[null,null,...]`となることを確認しました．これは，ログイン情報にてAPI_KEYの平文をぱっと見ではわかりにくくする仕様に起因します．ログインしている場合は(すくなくとも私の環境下では)[9642611, 9342112, 117412351]などといったintegersが入り，翻訳時は正常にもとのAPI_KEYで通信できることを確認しています．

**Comment by embeddedsamurai** [comment]
@T3aHat 

Chromeブラウザで，DeepLにログインした状態で，DeepLopener_PROのextensionのオプションにおいて
DeepL Pro API KEY に　キーをいれてTest を押すと，Error403 Authorization failedの状態になります。

**Comment by T3aHat** [comment]
@embeddedsamurai 
返信ありがとうございます．

私の説明不足でした．  
![syncon.png](https://github.com/T3aHat/DeepLopener_PRO/raw/main/gif/syncon.png)
のようにChromeにgoogleアカウントでログインしているかをお尋ねしました．
API_KEYの処理回りのデバッグを行ったver.1.0.2へストアの拡張機能を更新するので，(継続してご利用いただける場合は)こちらをお試しください．なお，ChromeWebStoreの審査がいつ終わるかは読めません(長いと１週間以上...)．    

READMEの[Install from GitHub](https://github.com/T3aHat/DeepLopener_PRO#install-from-github)の手順でインストールするとすぐにご利用いただけます．
![sampledebug.png](https://github.com/T3aHat/T3aHat.github.io/raw/master/assets/images/sampledebug.png)
2fcd8646678f6af714de5b3a9675912a3f49d883 の`options.js`にデバッグ用コードを追加しました．  
上の図のように`options`画面にて検証から`Console`を開いて`decrypted API_KEY`が入力したものと同じか確認してみてください．(図は適当なAPI_KEYを入力しているので403になっています)

**Comment by embeddedsamurai** [comment]
@T3aHat 

google accountを Sync is on にし, DeepLをログアウトした状態で
正常に動作しました。

あとDeepL opener PRO の option で  
Target language: 日本語  
で  
Englishに対して日本語に変換しました。
デフォルトが English(American)なので、そこを気づかない人もいるかもしれません。

**Comment by T3aHat** [comment]
動いて安心しました．  
ご報告ありがとうございました．  

英語→日本語をしたいユーザが，デフォルトだとTarget langがEnglish(American)なために翻訳されていないようにみえるということでしょうか?
Web版やアプリ版と異なり，API版だとその辺の言語切り替えの融通が利かないのが悩みどころです...

**Comment by embeddedsamurai** [comment]
@T3aHat 

>英語→日本語をしたいユーザが，デフォルトだとTarget langがEnglish(American)なために翻訳されていないようにみえるということでしょうか?

そのとおりです。ただ、それはちょっと試行錯誤すれば気づくかなとも思いました。

蛇足ですが、
pdf翻訳も試してみましたが、論文中の改行している部位がちゃんと一文として翻訳されていて
単純にpdfをコピペして，改行を消す手間が省けて論文読むのが捗ります。

以上解決しましたので、issueをcloseしてくださいませ。ありがとうございました。

**Comment by hibing2022** [comment]
I also

**Comment by T3aHat** [comment]
@hibing2022  
I'm sorry, but I don't have much information, so I can only give you some simple advice.

1. Are you entering the correct API_KEY?
2. Have you set the API version setting correctly to your API?
If the API_KEY ends with :fx, please specify Free.

You can check what kind of communication is actually being done by Chrome as follows.

1. Press `F12` button to open developer tools
2. Move to `NetWork`
3. Begin to record network activity by hit `Ctrl+R`
![image](https://user-images.githubusercontent.com/36735403/151654076-4cdfbd4c-ffda-4079-abdb-a8417d4fe88e.png)
4. Translate something (and may get 403 error)
![image](https://user-images.githubusercontent.com/36735403/151654158-86f73a57-b980-49f3-ba14-fb5c5519cc43.png)
5. check `translate`
  - Is `Request URL` correct?
    - Pro: https://api.deepl.com/v2/translate
    - Free: https://api-free.deepl.com/v2/translate
![Untitled](https://user-images.githubusercontent.com/36735403/151654440-1c836ee0-740d-4982-a943-c01e619aa361.png)
6. check `auth_key` on `Payload` 
![Untitled](https://user-images.githubusercontent.com/36735403/151654269-327c5ed5-7a32-4c76-84f5-0a2de3a020a4.png)
↑ I set `Pro` version and used Free API_KEY:fx so got error 403.

**Comment by hibing2022** [comment]
Thank you very much for your reply, I am the DeepL Pro Advanced
![image](https://user-images.githubusercontent.com/98624048/151672534-e8ae4b8c-1162-42da-9921-08ff4dd8fddf.png)

When I followed your method of tracking, I had the following alarms
![image](https://user-images.githubusercontent.com/98624048/151672645-58c94579-027f-4b2f-ba3b-6d81c65d5e9e.png)


![image](https://user-images.githubusercontent.com/98624048/151672590-c0daf483-933d-4dde-a4f6-64ccbec90f68.png)

Looking forward to your help

**Comment by T3aHat** [comment]
I thought API_KEY was not passed properly due to my bad implementation, but it looks like correct.
Umm... To be honest, I don't know why this error happens.

If you can get the translation result by accessing the URL below, it is a bug in my extension, but it is difficult to identify the cause. Otherwise, there is a problem with API_KEY, please contact DeepL.

https://api-free.deepl.com/v2/translate?auth_key=your_api_key&target_lang=ZH&tag_handling=xml&text=test

↑ Please change `your_api_key` to your API_KEY like `~186e`.

I'm sorry I can't give you a clear answer.

**Comment by hibing2022** [comment]
Thank you very much for your reply 

I entered the URL in my browser and I changed the URL http://api.deepl.com/
I was given the following information：

{"message":"Wrong endpoint. Use https://api.deepl.com"}

Not sure what this message means

**Comment by T3aHat** [comment]
Oh, sorry. Please try 
https://api.deepl.com/v2/translate?auth_key=your_api_key&target_lang=ZH&text=test

"Wrong endpoint" probably means that you should use https connection not http.

**Comment by hibing2022** [comment]
Thanks for your continued replies, I have contacted Deepl team and they have told me that the Key of DeepL Pro Advanced can only be used for CAT and not for the API. This is a strange result but at last we know the outcome!
